spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: myuser2
    password: mypassword2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: INFO
